# Generated by Django 4.1.2 on 2022-10-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Header')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('url', models.URLField(verbose_name='Link to ad')),
            ],
        ),
    ]
